### ISSUE TITLE
Feedback/Suggestion: RaspberryPi as Bluetooth to Wi-Fi link

### ISSUE THREAD

**Issue by rickoman** [apption-labs/meater-cloud-public-rest-api#1]
Has anyone at Apption-Labs considered the possibility of using a RaspberryPi as a MEATER Bluetooth to Wi-Fi Link?  This would be much cheaper than a "spare" phone or tablet.  It could be permanently deployed near the BBQ and be always available. Great product guys!

**Comment by Sotolotl** [comment]
I agree. The ability to ingress data to master cloud would be brilliant, meaning I could replace the chunky old 'spare' tablet withbut I dear it's unlikely to happen.

It'll be far too big a risk from Apption Lab's standpoint. Opening up the

**Comment by wire67** [comment]
Have you tried installing Android on rPi?

**Comment by apptionlabs** [comment]
Hi @rickoman 

It's always nice to hear from people who love our product. We have thought about this and it would be a cool to have but unfortunately not something we can really provide. 

If we did this, we'd want it to work as well as our MEATER products and apps. We'd need to provide support for this on top of the wide range of Android & iOS devices we currently support. Within our customer base there would be such a small number of users for this that it's just not viable.

We do already have MEATER Link for using spare devices and we have the MEATER Block for extra range over WiFi.

And as @Sotolotl rightly points out, we obviously don't want our internals being so easily accessible.
