### ISSUE TITLE
Documentation mistakes of the /devices endpoint

### ISSUE THREAD

**Issue by Novanic** [apption-labs/meater-cloud-public-rest-api#10]
There are mistakes at the documentation of the /devices endpoint.

1.) The attributes "target" and "peak" are within a "temperature" element when I test it via Postman. The "temperature" element is missing within example within the documentation.
2.) Possible values of the "state" attribute should get documented.

Thank you in advance.

**Comment by nojacko** [comment]
I've corrected the documentation for target and peak and added states.
