### ISSUE TITLE
Incorrect value for Ambient reported when not set by app

### ISSUE THREAD

**Issue by Sotolotl** [apption-labs/meater-cloud-public-rest-api#2]
When the app doesn't report an ambient temperature (see picture) then the API just returns the internal temperature for both internal and ambient measurements.

![Screenshot_20201001-193545](https://user-images.githubusercontent.com/8119869/94849565-85c86e80-041d-11eb-83a6-e212fccff29b.jpg)

Here is the response from the API in this case:

`{
    "status": "OK",
    "statusCode": 200,
    "data": {
        "id": "******************************",
        "temperature": {
            "internal": 22.4,
            "ambient": 22.4
        },
        "cook": null,
        "updated_at": 1601577350
    },
    "meta": {}
}`

I think the API should return null or no value in this case.

**Comment by apptionlabs** [comment]
This is expected behaviour that comes directly from the same data the apps use. Right now, ambient temperature has a minimum value of the internal temperature and when they are the same the apps show the dash. Once the ambient temperature rises above internal it will report the actual value.

**Comment by Sotolotl** [comment]
@apptionlabs Perfect, thanks for the clarification. I'll add the relevant logic to my code!

And thanks again for the great product, it's nice to see smart tech makers getting involved with the community and offering people the opportunity to expand and integrate into their own projects!

**Comment by nojacko** [comment]
Thanks! We saw requests coming into support for an API from a number of customers and... well here it is 😄 .

I've [updated](https://github.com/apption-labs/meater-cloud-public-rest-api/commit/039181ff0531216bba6f257f96b3296069378b9f) the README to include some additional information about this and some other things.
