### ISSUE TITLE
Can't connect/authorized to the meater cloud

### ISSUE THREAD

**Issue by LukasM937** [apption-labs/meater-cloud-public-rest-api#25]
After a break I want to work with the api, but for some reason I couldn't authorized to get a new token.

Now, I created a new Account, but still I'm not able to do so..

**Comment by simonmaddox** [comment]
Hey @LukasM937,

Can you share more information about what you're doing? I've just checked with my own account, and it _appears_ to work fine.

You can use this sample cURL command, from the README.md:

```
curl --location --request POST 'https://public-api.cloud.meater.com/v1/login' \
--header 'Content-Type: application/json' \
--data-raw '{
  "email": "<MEATER Cloud Email Address>",
  "password": "<MEATER Cloud Password>"
}'
```

Make sure to replace `<MEATER Cloud Email Address>` with the email address you used to register for MEATER Cloud, and replace `<MEATER Cloud Password>` with your account's password.

**Comment by LukasM937** [comment]
Seems to be a problem on my side.. I retry it and it works thank you anyways :)
