### ISSUE TITLE
The remaining time is always -1

### ISSUE THREAD

**Issue by marcorogo** [apption-labs/meater-cloud-public-rest-api#29]
Hi, the Meater app notifies the remaining time but via API the value is always -1.

**Comment by rafalkrol-xyz** [comment]
Hi, @marcorogo! Thanks for pointing this one out to us! It's now been corrected - could you please retry and let me know if it works for you?

**Comment by marcorogo** [comment]
Now everything works perfectly. Nice work! 💪🏼
