### ISSUE TITLE
API issue? Creating weblink?

### ISSUE THREAD

**Issue by Minxster** [apption-labs/meater-cloud-public-rest-api#30]
I don't know an easy way to check, but do you know why there was an API issue (main, not this public one) on Saturday (6th Nov)? I attempted to make a weblink from the app (several times) and it just wouldn't let me? A few folk have asked in a FB group I'm a member of, which reminded me of the issue 🤷‍♂️

Sorry for posting it here.

**Comment by rafalkrol-xyz** [comment]
Hi, @Minxster! Timeouts in Web Link functionality are a potential regression bug we have started noticing post our recent major release. We are currently focusing on optimising various aspects of MEATER Cloud, with under-the-hood upgrades shipping almost daily. The recent batch of these should help stabilise the Web Link experience, especially during busier periods like weekends. Thus, I will close this issue for now, but please reopen it if the problem prevails.
