### ISSUE TITLE
Previous Cooks feature

### ISSUE THREAD

**Issue by Minxster** [apption-labs/meater-cloud-public-rest-api#32]
Sorry to post here, since this is for the public/open API. But I did ask a little while ago about some issues with Previous Cooks and the cooking temperatures being messed up. But today, when looking in the app, just about all of my Previous Cooks have disappeared?

I'm guessing they're both related? Was all of this made public? E.g. an email to customers?

Is there any way to get the data back, even if it's just a download so I can recover the data myself?

**Comment by simonmaddox** [comment]
@Minxster apologies for the delay, I've only just spotted this. Given that you've closed this issue, does that mean that your previous cooks have returned?

**Comment by Minxster** [comment]
> @Minxster apologies for the delay, I've only just spotted this. Given that you've closed this issue, does that mean that your previous cooks have returned?

No worries at all 🙂 I'd posted in different places (and a support ticket), for this issue and given this is for the open API, I thought I'd just close it 😉 The issue is known with no ETA on a fix.

Anywho, it makes sense to close this down. Thanks for getting back to me, but you can go back to your eggnog 👍😁😹 Have a great festival season ♥️

**Comment by simonmaddox** [comment]
Can you Pull To Refresh on the Previous Cooks screen? It _might_ be fixed 🤞🏻

**Comment by Minxster** [comment]
> Can you Pull To Refresh on the Previous Cooks screen? It _might_ be fixed 🤞🏻

It didn't work at all until I got the email response from web support. I suspect using the same email address helped the to get things unlock 🤣😁 It's obviously still wrong data, but I can redo the math ♥️

At least I now know how long a rib of beef joint took last Xmas 😋🙂
